### PR TITLE
Adjust volume on button press

### PR DESCRIPTION
**Pull request by JinShil**
The volume widget's handle is too difficult to grab with a finger using a touch screen.  Please accept this pull request so that an operator can adjust the volume by simple touching (or clicking) any point along the length of the volume widget without having to grab the widget's handle first.  This new behavior is also congruent with the way volume widgets work on most other platforms.

### CODE REVIEW

**Comment by spl237** [comment]
This looks like a worthwhile change - thank you.

One word of caution - we are currently working on the forthcoming Bookworm release of RPiOS and are only doing security maintenance on the current Bullseye release, so this may have to wait until Bookworm to be released.

**Comment by arturo182** [comment]
Am I correct to assume that the Bookworm fix would be implemented here: https://github.com/raspberrypi-ui/wf-panel-pi/blob/master/src/panel/widgets/volumepulse/commongui.c#L138 ?

If so, I would be happy to port this solution to the new repo :)

**Comment by JinShil** [comment]
> If so, I would be happy to port this solution to the new repo :)

Please do.

**Comment by spl237** [comment]
On thinking further about this, I am unconvinced that this is an adequate fix for the problem. While I can see that on a high-resolution touchscreen, it may indeed be difficult to grab the handle, it will also be difficult to accurately set the volume by tapping at some point on what will be a relatively short scale.

While I am not denying that there is a potential problem with touchscreens here, I don't think this offers a real solution to it, and some alternative such as volume up/down buttons being provided would be better. I will consider how such could be made available in a possible alternative plugin.

**Comment by arturo182** [comment]
TBH my problem comes not from using a touch screen, but from a thumb trackpad, where it's hard to hold and drag, so just clicking on the bar would be very useful.

**Comment by spl237** [comment]
Also, on testing this behaviour on touchscreens, under Wayland, the volume slider already implements this behaviour anyway.

**Comment by spl237** [comment]
In fact, now I test on X11 as well, the volume slider also responds to touch clicks - no need to drag on their either. So I'm not sure why this PR was necessary for you - perhaps something about your particular touch screen?

**Pull request closed without merging**
